export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_5_DAYS_FORECAST = "GET_5_DAYS_FORECAST";
export const SET_CITY_ID = "SET_CITY_ID";
export const SET_CITY_NAME = "SET_CITY_NAME";
export const TOGGLE_DEGREE_TYPE = "TOGGLE_DEGREE_TYPE";
